wcc -ml -0 -os -I. main.c > main.out
wcc -ml -0 -os -I. timer.c > timer.out
wcc -ml -0 -os -I. video.c > video.out
wcc -ml -0 -os -I. palette.c > palette.out
wcc -ml -0 -os -I. graphics.c > graphics.out
wcc -ml -0 -os -I. font.c > font.out
wcc -ml -0 -os -I. fontdata.c > fontdata.out
wcc -ml -0 -os -I. scene.c > scene.out
wcc -ml -0 -os -I. scenes\scene1.c > scene1.out
wcc -ml -0 -os -I. scenes\scene2.c > scene2.out
wcc -ml -0 -os -I. scenes\scene3.c > scene3.out
wlink @LINK.RSP > link.out
